### PR TITLE
[#3570]: Content - No Content Page Layout Fix

### LINKED ISSUE #3570: Content: No Content Page Layout Fix
### Description:
The "No Content Page" currently uses justify-content: space-between, which causes the layout to stretch awkwardly on larger screens.

Image

Steps to Reproduce:
- Go to page http://8-f48cf3a682-7fthvk.manager.dev.zesty.io:8080/content/6-8aafd5e286-f5n04f?lang=en-US

Fix:
Center the components and apply appropriate horizontal margins for better visual balance.

### PR DESCRIPTION
**Pull request by geodem127**
- [ ] Center the components and apply appropriate horizontal margins for better visual balance.

BEFORE:
image

AFTER:
image

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemList/ItemListEmpty.tsx [hunk 1]
```diff
@@ -7,33 +7,35 @@ export const ItemListEmpty = () => {
...
-          color="primary"
-          startIcon={<Add />}
-          size="small"
-          onClick={() => {
-            history.push(`/content/${modelZUID}/new`);
-          }}
-        >
-          Create
-        </Button>
+    <Container maxWidth="lg" disableGutters sx={{ height: "100%" }}>
```
Comment (agalin920) [inline src/apps/content-editor/src/app/views/ItemList/ItemListEmpty.tsx:10]: Seems a bit odd to me we would setup a max width container only on this empty view. Is this a standard we do across all our empty views?

Comment (geodem127) [reply src/apps/content-editor/src/app/views/ItemList/ItemListEmpty.tsx:10]: yes. we’ve recently applied similar layout updates to the "Empty Fields" and "GA Connect" pages.
Would it be more appropriate to use a Box and center its contents directly, rather than relying on the Container component for this layout?

**Review by agalin920 — APPROVED** [review]
