### PR TITLE
Settings: support dirty state, refactors and bugfixes

### LINKED ISSUE #496: Settings: font not installing in webpage <head>
**Describe the bug**
When a user installs a font through Settings -> Fonts, then selects it through Settings -> Styles -> Typography - the selection saves but the font is *not* installed in the head, therefore although it is in the stylesheet it doesn't render because it's not linked in the <head>. 

**To Reproduce**
Before you begin ensure that the stylesheet is setup to use the the Style variables.
1. Go to Settings -> Fonts -> Browse Fonts
2. Select a recognizable font to add to your instance and save
3. Navigate to Settings -> Styles -> Typography & select the font you added in step 2 and save. 
4. Open the dev preview and notice that the new font is not being used, even though you'll see it referenced in the stylesheet if you inspect the page.
5. Go to Settings -> Head Tags and notice that the font you added in steps 2/3 is not listed there. 

**Expected behavior**
When fonts are added through Settings -> Fonts and then selected through Settings -> Styles -> Typography the font should be referenced in the `<head>`.

**Screenshots**
How it's working now:
google-fonts-issue-2

How it _should_ work:
google-font-issue

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 88??

**Additional context**

### LINKED ISSUE #503: Settings: Error on sub category
**Describe the bug**
In Manager UI clicking into Settings > Styles > any category will return an error message

**To Reproduce**
1. Manager UI
2. Settings
3. Scroll down to Styles
4. Click any sub category
5. See error message

**Expected behavior**
Expect to see styles load per sub category selected.

**Screenshots**
https://www.loom.com/share/9ea4a32dd61b48aba85bed4bef42c73a

**Desktop (please complete the following information):**
 - OS: Mac Big Sur
 - Browser: safari + chrome

### PR DESCRIPTION
**Pull request by nibblebot**
- feat: browse fonts selecting variants enables 'Add' button
- feat: instance settings add dirty state, save only dirty fields, disable save button if not dirty, clear dirty on save
- feat: style settings disable save button if not dirty, clear dirty on save
- refactor: style settings - remove extraneous fetchStyleVariables (since we persist settings updates to store)
- refactor: rename state and functions for clarity
- refactor: browse fonts - remove unused state
- refactor: remove extraneous imports
- refactor: instance settings - remove dead Tooltip code
- fix: settings save notification text
- fix: no search results text, no installed fonts text
- fix: browse fonts variant selection
- fix: installing font uses associated instance ZUID for head tag
- fix: installed fonts and styles settings - allow handling of previously installed fonts with no variants
- fix: style settings - persist settings updates to redux store

fixes #503 
fixes #496

### CODE REVIEW

File: src/apps/settings/src/app/views/Fonts/Browse.js [hunk 1]
```diff
@@ -182,27 +181,35 @@ export default connect(state => {
...
+      };
+      if (fontVariants.length) {
+        newVariants[font] = fontVariants;
+      } else {
+        delete newVariants[font];
+      }
     }
-    console.log("varians selected", variantsSelected);
+    setVariants(newVariants);
+    console.log("variants selected", newVariants);
```
Comment (shrunyan) [inline src/apps/settings/src/app/views/Fonts/Browse.js:212]: Remove log

File: src/apps/settings/src/app/views/Fonts/Browse.js [hunk 2]
```diff
@@ -215,7 +222,7 @@ export default connect(state => {
                 <h3 className={styles.FontFamily}>{itemFont.family}</h3>
                 <ul className={styles.FontVariants}>
                   {itemFont.variants.map((item, index) => (
-                    <li key={`${itemFont.family}-${index}`}>
+                    <li key={`${itemFont.family}-${item}`}>
```
Comment (shrunyan) [inline src/apps/settings/src/app/views/Fonts/Browse.js:225]: What is `item`? Is this something we should be adding into a component key? i.e. is this a string?

File: src/apps/settings/src/app/views/Fonts/Browse.js [hunk 3]
```diff
@@ -233,9 +240,9 @@ export default connect(state => {
                   id="InstallFont"
                   className={styles.SaveBtn}
                   onClick={() => onUpdateFont(itemFont.family)}
-                  disabled={isLoading}
+                  disabled={saving || !variantsSelected[itemFont.family]}
                 >
-                  {isLoading ? (
+                  {saving ? (
                     <FontAwesomeIcon icon={faSpinner} />
```
Comment (shrunyan) [inline src/apps/settings/src/app/views/Fonts/Browse.js:246]: Add the `spin` attribute provided by font awesome to animate this icon

File: src/apps/settings/src/app/views/Fonts/Installed.js [hunk 4]
```diff
@@ -170,13 +173,32 @@ export default connect(state => {
...
             </header>
+            {font.variants.length === 0 && (
+              <div style={{ display: "flex", justifyContent: "space-between" }}>
+                <p
+                  className={styles.ParagraphFontInstalled}
+                  style={{
+                    fontFamily: font.font.replace("+", " ")
+                  }}
+                >
+                  All their equipment and instruments are alive.
```
Comment (shrunyan) [inline src/apps/settings/src/app/views/Fonts/Installed.js:184]: What is this?

**Review by shrunyan — CHANGES_REQUESTED** [review]

File: src/apps/settings/src/app/views/Fonts/Browse.js (hunk 2 above)
Comment (nibblebot) [reply src/apps/settings/src/app/views/Fonts/Browse.js:225]: this is an item weight number

File: src/apps/settings/src/app/views/Fonts/Installed.js (hunk 4 above)
Comment (nibblebot) [reply src/apps/settings/src/app/views/Fonts/Installed.js:184]: there are some instances that have somehow installed a Font without a weight/variant.
This new code adds a Remove button to these installed fonts, so it can be cleaned up.

**Review by shrunyan — APPROVED** [review]
