### PR TITLE
[Leads] - TypeError: e.dispatch(...).finally is not a function

### LINKED ISSUE #3515: TypeError: e.dispatch(...).finally is not a function
Sentry Issue: [MANAGER-UI-2DK](https://zestyio.sentry.io/issues/6614699755/?referrer=github_integration)

```
React ErrorBoundary Error: e.dispatch(...).finally is not a function
  at FT (./src/apps/leads/src/app/views/Leads/Leads.js:15:33)
  at VA (./src/shell/views/Shell/Shell.tsx:37:20)
  at Vi (./src/shell/components/load-instance/index.js:33:31)
  at wi (./src/shell/components/private-route/index.js:34:15)
  at CreateContentItemDialogProvider (./src/shell/contexts/CreateContentItemDialogProvider.tsx:21:3)
...
(19 additional frame(s) were not displayed)

TypeError: e.dispatch(...).finally is not a function
  at h (./src/apps/leads/src/app/views/Leads/Leads.js:19:5)
...
(9 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by geodem127**
RCA: 
- [x] fetchLeads didn't return values, breaking the promise chain.

FIX:
- [x] Added return sortedLeads and throw err in the action
- [x] Wrapped dispatch in Promise.resolve() to guarantee .finally exists

### CODE REVIEW

File: src/apps/leads/src/store/leads.js [hunk 1]
```diff
@@ -40,6 +41,7 @@ export function fetchLeads() {
             message: err.message,
           })
         );
+        throw err;
```
Comment (finnar-bin) [inline src/apps/leads/src/store/leads.js]: Is this error handled somewhere? Otherwise this will cause some noise on Sentry.

**Review by finnar-bin — APPROVED** [review]
