### PR TITLE
Content: refactor ItemList to functional

### LINKED ISSUE #362: Content: ItemList single item should redirect to ItemEdit
currently redirects via window.location.hash which doesn't work,
should be a history.push to the correct itemZUID

### PR DESCRIPTION
**Pull request by nibblebot**
fixes #362

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 1]
```diff
@@ -56,708 +63,629 @@ export default connect((state, props) => {
...
-      height: 1000,
-      width: 1000,
-      sortedBy: null,
-      status:
-        (this.props.filters[this.props.modelZUID] &&
-          this.props.filters[this.props.modelZUID].status) ||
-        "all"
+})(function ItemList(props) {
+  const history = useHistory();
+  const _isMounted = useRef(false);
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:68]: What is the purpose of using a ref when later it is just boolean evaluation?

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 2]
```diff
@@ -56,708 +63,629 @@ export default connect((state, props) => {
...
+  // table, list dimensions
+  const table = useRef();
+  const list = useRef();
+  const [height, setHeight] = useState(1000);
+  const [width, setWidth] = useState(1000);
+
+  // saving, loading states
+  const [saving, setSaving] = useState(false);
+  const [loading, setLoading] = useState(false);
+  const [loadingSecondary, setLoadingSecondary] = useState(false);
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:79]: Lets give line 78 & 79 more semantic names. Ideally they would communicate what they are affecting when in a loading state.

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 3]
```diff
@@ -56,708 +63,629 @@ export default connect((state, props) => {
...
-        modelZUID: this.props.modelZUID,
-        filters: {
-          filterTerm: this.state.filterTerm,
-          sortedBy: this.state.sortedBy,
-          status: this.state.status,
-          colType: this.state.colType,
-          reverseSort: this.state.reverseSort
-        }
-      });
+  // HACK: runFilters after waiting for new props
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:136]: The majority of places where you have included a `// HACK` comment need more information on why it is a hack. 
e.g. > runFilters after waiting for new props

Is this a hack vs running the filters synchronously? The "hack" on the `useEffect` is confusing because what is described is the default behavior of `useEffect`. i.e. waiting for new props.

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 4]
```diff
@@ -56,708 +63,629 @@ export default connect((state, props) => {
...
+    setLoadingSecondary(true);
+
+    try {
+      const [, itemsRes] = await Promise.all([
+        props.dispatch(fetchFields(modelZUID)),
+        props.dispatch(fetchItems(modelZUID, { limit: PAGE_SIZE, page: 1 }))
+      ]);
+      if (_isMounted.current) {
+        // render 1st page of results
+        // HACK: runFilters after waiting for new props
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:193]: Is this trying to communicate that filters will be run at the next render cycle vs that code executing immediately?

**Review by shrunyan — APPROVED** [review]
Overall a welcomed improvement to the code structure and readability of this component. I've left a few comments. Also would you give this another once over now that you have had to look at it for awhile. See if anything pops out. Otherwise this looks ready to go.

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js (hunk 1 above)
Comment (nibblebot) [reply src/apps/content-editor/src/app/views/ItemList/ItemList.js:68]: ref will retain it's value across renders unlike a regular variable

Comment (shrunyan) [reply src/apps/content-editor/src/app/views/ItemList/ItemList.js:68]: Wouldn't `useState` have the same behavior? 

My concern with a ref is weight and possibility of a memory leak. Meaning under the hood I assume react is allocating more resources when generating a ref vs state. Could there be a potential for memory leaks if `ref` references are being maintained. i.e. Could this create detached DOM nodes?  Maybe a non issue as the ref is not being attached to a DOM node. p.s. I don't have any authoritative answers to these theoretical questions, just posing thoughts for consideration. I'm not viewing this as a blocker

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 5]
```diff
@@ -56,708 +63,630 @@ export default connect((state, props) => {
...
+  // table, list dimensions
+  const table = useRef();
+  const list = useRef();
+  const [height, setHeight] = useState(1000);
+  const [width, setWidth] = useState(1000);
+
+  // saving, loading states
+  const [saving, setSaving] = useState(false);
+  const [loadingFirstPage, setLoadingFirstPage] = useState(false);
+  const [loadingSecondaryPages, setLoadingSecondaryPages] = useState(false);
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:79]: I am still not clear on these. What is a page? An app screen or an API page? Would something like `initialLoad` and `backgroundLoad` explain what these deal with?

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 6]
```diff
@@ -190,24 +188,26 @@ export default connect((state, props) => {
       ]);
       if (_isMounted.current) {
         // render 1st page of results
-        // HACK: runFilters after waiting for new props
+        // HACK: runFilters next render cycle with fresh props/state
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:191]: Still not sure I'm following why this is a "hack" as it is the default behavior on setting state. **Unless I'm missing something**.

If the intent is to document the flow of this code as it can be complex for those learning React I would suggest these all get moved up to where the state is initialized and describe the flow without noting it is a hack. Also include why we are describing the flow that is standard behavior. This should also help with the repetition of these comments.

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js (hunk 1 above)
Comment (nibblebot) [reply src/apps/content-editor/src/app/views/ItemList/ItemList.js:68]: changes to `useState` triggers re-render whereas changes to a `ref` does not. `useRef` is the standard way to track isMounted in functional components (vs. class components which can use instance variables)
prior art: https://dev.to/tusharkashyap63/use-refs-to-check-if-a-component-is-still-mounted-2gk7 http://naomiajacobs.com/useRef-vs-useState/
since we are tracking a boolean here there is no worry about detached dom nodes.

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js (hunk 5 above)
Comment (nibblebot) [reply src/apps/content-editor/src/app/views/ItemList/ItemList.js:79]: initial/background Load works for me
