### PR TITLE
[#3799]: Blocks - Unable to sort media assets of a media field

### LINKED ISSUE #3799: Blocks - Unable to sort media assets of a media field
## Problem

Re-ordering media assets under a media field is making the media asset disappear which makes re-ordering not possible

- [Slack conversation link](https://zesty-io.slack.com/archives/C050120G5/p1758738607926639)
- [Block variant](https://8-928ba7ffc1-445x05.manager.zesty.io/blocks/6-8ae6c2a182-c74wlt/7-849aadb2fd-gdh1g7)

## Screenshots

- [Video demo](https://zesty-io.slack.com/files/U05U2LANDBK/F09H3LG4VTN/re-ordering_media_field_with_multiple_media_assets.mov)

## Steps to reproduce

1. Go to the block variant
2. Re-order the media assets under the Desktop Media field

## Expected behavior

User should be able to re-order the media assets.

## Additional Notes

It is only happening on this specific instance - 8-928ba7ffc1-445x05. I tested on my other test instances and it is working fine.

### LINKED ISSUE #3845: [Schema] - Application Crashes When Adding New Relational Fields
## Problem
The application experiences crashes when adding new relational field

## Recording
https://github.com/user-attachments/assets/179ebb17-3534-4490-b863-09ea764dce28

## Steps to reproduce
1. Navigate to Schema → Open any model
2. Add a new relational field (one-to-one or one-to-many)
3. Configure reference model and display field
4. Go to Rules tab
5. Set default values
6. Add field items
7. Click "Add Field" - Application crashes

## Expected behavior
Application should remain stable when adding relational fields

### PR DESCRIPTION
**Pull request by geodem127**
## Root Cause:
Native HTML5 drag events were conflicting with React DnD's event system when multiple drag and drop components were introduced.

## Fix:

Created a dedicated DndContextProvider component to properly handle root element context

This allows multiple HTML5Backend instances to coexist without conflicts

https://github.com/user-attachments/assets/fa872f9b-f2ab-4e75-bf4b-98528061dcf2

https://github.com/user-attachments/assets/f9a28ed8-4c26-41dd-b0ba-a92654a94626

### CODE REVIEW

**Review by agalin920 — APPROVED** [review]

File: src/shell/components/RelationalFieldBase/index.tsx [hunk 1]
```diff
@@ -121,7 +121,7 @@ export const RelationalFieldBase = ({
             <ActiveItemLoading key={index} draggable />
           ))
         ) : (
-          <DndProvider backend={HTML5Backend}>
+          <DndProvider backend={HTML5Backend} key={name}>
```
Comment (finnar-bin) [inline src/shell/components/RelationalFieldBase/index.tsx]: What is the purpose of the key prop here?

File: src/shell/components/DndContextProvider.tsx [hunk 2]
```diff
@@ -0,0 +1,21 @@
...
+import { DndProvider } from "react-dnd";
+import { HTML5Backend } from "react-dnd-html5-backend";
+
+const DndContextProvider = memo(
+  ({ id, children }: { id?: string; children: React.ReactNode }) => {
+    const [context, setContext] = useState(null);
+
+    useEffect(() => {
+      setContext(document.getElementById(id));
+    }, [id]);
```
Comment (finnar-bin) [inline src/shell/components/DndContextProvider.tsx]: I suggest throwing an error here if the ID is missing since it's necessary to properly set the context for the dnd provider

**Review by finnar-bin — CHANGES_REQUESTED** [review]

File: src/shell/components/DndContextProvider.tsx (hunk 2 above)
Comment (geodem127) [reply src/shell/components/DndContextProvider.tsx]: I don't think an error is necessary here. The id is guaranteed because it's either a required field name from the data model, which is always present and unique, or it's being set explicitly in the component.

File: src/shell/components/RelationalFieldBase/index.tsx (hunk 1 above)
Comment (geodem127) [reply src/shell/components/RelationalFieldBase/index.tsx]: removed

**Review by finnar-bin — APPROVED** [review]
