### PR TITLE
[#3438] Redirects: Import CSV/XML - DIsplay Error when File Import Fails

### LINKED ISSUE #3438: Redirects: Import CSV/XML - DIsplay Error when File Import Fails
# Problem
The Redirects App currently lacks informative error feedback when users attempt to import CSV or XML files that fail validation. This leaves users without clear understanding of the issue or guidance on how to correct it.

# Solution
If the import now fails we display a modal that says: 
- File Import Failed
- The file format or structure doesn’t match what we expected. Please check your CSV or XML file and refer to our import guide in our docs for the correct format.

Image

# Dev Notes
Documentation Link: https://docs.zesty.io/docs/redirects#mass-redirect

# Figma
https://www.figma.com/design/9tiAwQg179ezJH48diVdph/Redirects-App?node-id=60-36671&t=X9cqEkZigmLQs57v-1

### PR DESCRIPTION
**Pull request by geodem127**
### If the import now fails we display a modal that says:
- [x] File Import Failed
- [x] The file format or structure doesn’t match what we expected. Please check your CSV or XML file and refer to our import guide in our docs for the correct format.

https://github.com/user-attachments/assets/b8057ea5-3532-4dcc-a69f-0dd0f13d8762

### CODE REVIEW

**Review by agalin920 — APPROVED** [review]

File: src/apps/seo/src/views/RedirectsManager/RedirectActions/RedirectsImport.tsx [hunk 1]
```diff
@@ -0,0 +1,186 @@
...
+    try {
+      const file = files[0];
+      const importRes = await importCSVFile(file, redirects, dispatch);
+
+      if (importRes.status === "error") {
+        dispatch({ type: IMPORT_REDIRECTS, redirects: [] });
+        setIsDialogOpen(true);
+        return;
+      }
+      await new Promise((resolve) => setTimeout(resolve, 100));
```
Comment (finnar-bin) [inline src/apps/seo/src/views/RedirectsManager/RedirectActions/RedirectsImport.tsx]: Is this delay really necessary?

File: src/apps/seo/src/views/RedirectsManager/RedirectActions/RedirectsImport.tsx [hunk 2]
```diff
@@ -0,0 +1,186 @@
...
+      dispatch({ type: IMPORT_REDIRECTS, redirects: importRes.targets });
+      clearFiles();
+      setIsDialogOpen(false);
+    } catch (error) {
+      console.error("Import failed:", error);
```
Comment (finnar-bin) [inline src/apps/seo/src/views/RedirectsManager/RedirectActions/RedirectsImport.tsx]: Remove if this is just for testing

**Review by finnar-bin — APPROVED** [review]
