### PR TITLE
[Content] Handle error when fields fail to load

### LINKED ISSUE #3230: TypeError: Cannot read properties of undefined (reading 'length')
Sentry Issue: [MANAGER-UI-2BD](https://zestyio.sentry.io/issues/6286408319/?referrer=github_integration)

```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'length')
  at Meta (./src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx:110:6)
  at AIGeneratorProvider (./src/shell/components/withAi/AIGeneratorProvider.tsx:39:39)
  at ItemEdit (./src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:80:20)
  at wI (./src/apps/content-editor/src/app/ContentEditor.js:102:22)
  at FU (./src/shell/views/Shell/Shell.tsx:33:20)
...
(31 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'length')
  at metaFields (./src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx:135:18)
  at Meta (./src/apps/content-editor/src/app/views/ItemEdit/Meta/index.tsx:134:24)
...
(14 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by finnar-bin**
Handles error when the api call to fetch fields fail
Fixes #3230 

Screenshot from 2025-02-26 11-53-13

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js [hunk 1]
```diff
@@ -170,6 +170,17 @@ export default function ItemEdit() {
     setSEOErrors({});
   }, [location.pathname]);
 
+  useEffect(() => {
+    if (fieldsLoadingError) {
```
Comment (agalin920) [inline src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:174]: Is this something we need to account for? If so I think we should lift this at a higher level because then it begs the question why do we show a toast here but no where else where we fetch fields

**Review by agalin920 — CHANGES_REQUESTED** [review]

File: src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js (hunk 1 above)
Comment (finnar-bin) [reply src/apps/content-editor/src/app/views/ItemEdit/ItemEdit.js:174]: You mean like show a toast error when **this** api call fails? 

Actually, this was something I personally decided on adding here since the editor loads and shows the no fields component. I thought it might confuse users thinking that someone deleted all their model's fields therefore showing that error message would immediately let them know that it was just a network issue.

I was actually thinking if there's like a way to make a notification dispatch like this within the rtk query itself so we don't have make the notif dispatch individually on each component but I'm kind of torn since I feel like it's not something the rtk query should be responsible.

**Review by agalin920 — APPROVED** [review]
