### PR TITLE
[#3679]: Blocks - Can't duplicate any variant of a Block 

### LINKED ISSUE #3679: Blocks - Can't duplicate any variant of a Block
## Problem

Instance: 8-928ba7ffc1-445x05
Block: 7-f8dcf7a6df-4hq7sc

When trying to duplicate any variant of that block, we get an error "Failed to duplicate block variant" error. Upon checking the network tab, there's a failed request to /items showing with this error:

```
{
    "_meta": {
        "timestamp": "2025-07-25T15:03:21.265421066Z",
        "totalResults": 1,
        "start": 0,
        "offset": 0,
        "limit": 1
    },
    "data": {},
    "error": "Bad Request: validation error: Unable to create item: Field doesn't exist: title"
} 
```

The block had a deactivated field which had that required rule but even after removing that required rule, the error still persist. 

## Screenshots

Image

### PR DESCRIPTION
**Pull request by geodem127**
RCA:
- [ ] missing filter for deactivated fields

Fix:
- [ ] Implement logic to filter out deactivated fields.

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx [hunk 1]
```diff
@@ -39,16 +42,27 @@ export const DuplicateItemDialog = ({ onClose }: DuplicateItemProps) => {
   const [createContentItem, { isLoading }] = useCreateContentItemMutation();
 
   const duplicateItem = () => {
+    const activeFields =
+      modelFields?.filter((field) => !field?.deletedAt) || [];
```
Comment (agalin920) [inline src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx]: Can't we fetch fields without the show deleted parameter?

**Review by agalin920 — CHANGES_REQUESTED** [review]

File: src/shell/services/instance.ts [hunk 2]
```diff
@@ -336,14 +336,23 @@ export const instanceApi = createApi({
       invalidatesTags: ["ContentModels", "ContentNav"],
     }),
     // https://www.zesty.io/docs/instances/api-reference/content/models/#Get-Fields
-    getContentModelFields: builder.query<ContentModelField[], string>({
-      query: (modelZUID) =>
-        `content/models/${modelZUID}/fields?showDeleted=true`,
+    getContentModelFields: builder.query<
+      ContentModelField[],
+      string | { modelZUID: string; showDeleted?: boolean }
```
Comment (finnar-bin) [inline src/shell/services/instance.ts]: Is there any specific reason why the param is open to both a string and object being passed in instead of just 1 type?

Comment (geodem127) [reply src/shell/services/instance.ts]: It is just to allow the query with just the modelZUID so we no longer need to update other components that uses that query function.

**Review by finnar-bin — APPROVED** [review]

File: src/shell/services/instance.ts [hunk 3]
```diff
@@ -336,14 +336,23 @@ export const instanceApi = createApi({
...
+    >({
+      query: (args) => {
+        const modelZUID = typeof args === "string" ? args : args.modelZUID;
+        const showDeleted =
+          typeof args === "string" ? true : args.showDeleted ?? true;
+
+        return `content/models/${modelZUID}/fields?showDeleted=${showDeleted}`;
```
Comment (agalin920) [inline src/shell/services/instance.ts]: please use the rtk query pattern for applying params

**Review by agalin920 — CHANGES_REQUESTED** [review]

File: src/shell/services/instance.ts (hunk 2 above)
Comment (agalin920) [reply src/shell/services/instance.ts]: I would say we should update past uses if we do plan on doing this. Supporting two types incurs tech debt. cc: @finnar-bin

**Review by agalin920 — CHANGES_REQUESTED** [review]

**Review by finnar-bin — APPROVED** [review]

**Review by agalin920 — APPROVED** [review]
