### PR TITLE
[Content]: Publish status chip in data table not displaying correctly

### LINKED ISSUE #3818: Content - Publish status chip in data table not displaying correctly
## Problem

There is an issue with the display of the published status in the data table (content grid) where items that are already published are initially shown in the unpublished state (blue chip).

This behavior makes it difficult for users to accurately isolate unpublished items when reviewing content in the grid, leading to confusion and unnecessary validation steps.

- see affected content item table [here](https://8-eae68eeef3-7q6bpc.manager.zesty.io/content/6-c4998c9d93-wtqfwv?lang=en-AU)

## Screenshots/video reference

https://github.com/user-attachments/assets/0839b848-7222-4113-952f-296410e63bc5

## Steps to reproduce

1. Navigate to a content data table/grid, see example [content item table](https://8-eae68eeef3-7q6bpc.manager.zesty.io/content/6-c4998c9d93-wtqfwv?lang=en-AU) 
2. Observe the content items publish status. Several items that are known to be published will display the blue unpublished status indicator.
3. Click on one of these items to open the content editor and confirm it is published.
4. Navigate back to the data grid.

**Note:** I haven't replicated this in my test instance, issue could be related to long-list of items in table or using multiple locales

## Expected behavior

The content item's status indicator in the data table/grid should accurately reflect its true published status (i.e., display the green published status if the item is published) immediately upon initial page load.

### PR DESCRIPTION
**Pull request by geodem127**
## RCA: 
The initial implementation encountered API limitations when retrieving publishing records

## FIX:
- [x] Created a new API endpoint to fetch publishing records per model.
- [x] Replaced the front-end Redux action fetchItemPublishings with fetchModelItemsPublishings to use the new endpoint.

## Prerequisite:
This change is dependent on the instances-api PR being merged first.
PR: https://github.com/zesty-io/instances-api/pull/689

### CODE REVIEW

File: src/shell/store/content.js [hunk 1]
```diff
@@ -977,7 +977,7 @@ export function fetchItemPublishings() {
   return (dispatch) => {
     return dispatch({
       type: "FETCH_RESOURCE",
-      uri: `${CONFIG.API_INSTANCE}/content/items/publishings?limit=100000`,
+      uri: `${CONFIG.API_INSTANCE}/content/items/publishings?limit=20000`,
```
Comment (agalin920) [inline src/shell/store/content.js]: Can we add a comment to clearly delineate this is the upper bound.

How as this upper bound determined?

File: src/shell/store/content.js [hunk 2]
```diff
@@ -1008,6 +1008,51 @@ export function fetchItemPublishings() {
     });
   };
 }
+export function fetchModelItemsPublishings({
+  modelZUID,
+  limit = 10000,
```
Comment (agalin920) [inline src/shell/store/content.js]: Same here.

File: src/shell/store/content.js [hunk 3]
```diff
@@ -1008,6 +1008,51 @@ export function fetchItemPublishings() {
...
+  showDeleted = false,
+  showDeletedItems = false,
+  showActiveOnly = false,
+}) {
+  return (dispatch) => {
+    console.debug("dispatch", { dispatch });
```
Comment (agalin920) [inline src/shell/store/content.js]: debug log

**Review by agalin920 — CHANGES_REQUESTED** [review]

File: src/shell/store/content.js (hunk 1 above)
Comment (finnar-bin) [reply src/shell/store/content.js]: Has this limit been tested on a big instance? Just wanted to make sure it isn't causing any performance issues

File: src/shell/store/content.js [hunk 4]
```diff
@@ -1008,6 +1008,51 @@ export function fetchItemPublishings() {
...
+    return dispatch({
+      type: "FETCH_RESOURCE",
+      uri: `${CONFIG.API_INSTANCE}/content/models/${modelZUID}/items/publishings?limit=${limit}&showDeleted=${showDeleted}&showDeletedItems=${showDeletedItems}&showActiveOnly=${showActiveOnly}`,
```
Comment (finnar-bin) [inline src/shell/store/content.js]: I would suggest creating a new URLSearchParams to store all the search params as an object then using the `toString()` to make it more readable and easier to maintain as there's several params involved

**Review by finnar-bin — CHANGES_REQUESTED** [review]

File: src/shell/store/content.js (hunk 1 above)
Comment (geodem127) [reply src/shell/store/content.js]: Reduce the initial load to 10k since model-scoped fetching on navigation has already been implemented.

File: src/shell/store/content.js (hunk 2 above)
Comment (geodem127) [reply src/shell/store/content.js]: updated. added comment

File: src/shell/store/content.js (hunk 3 above)
Comment (geodem127) [reply src/shell/store/content.js]: removed

File: src/shell/store/content.js (hunk 4 above)
Comment (geodem127) [reply src/shell/store/content.js]: updated

File: src/shell/store/content.js [hunk 5]
```diff
@@ -1009,6 +1010,71 @@ export function fetchItemPublishings() {
...
+  limit = 10000, //set 10k limit as optimal threshold for 2-second response times
+  showDeleted = false,
+  showDeletedItems = false,
+  showActiveOnly = false,
+}) {
+  const params = new URLSearchParams({
+    limit: limit.toString(),
+    showDeleted: showDeleted.toString(),
+    showDeletedItems: showDeletedItems.toString(),
+    showActiveOnly: showActiveOnly.toString(),
```
Comment (finnar-bin) [inline src/shell/store/content.js]: Is adding `.toString()` on each value necessary?

Comment (geodem127) [reply src/shell/store/content.js]: No, .toString() is not necessary. The PR has been updated to remove these

**Review by agalin920 — APPROVED** [review]

**Review by finnar-bin — APPROVED** [review]
