### PR TITLE
[#3820]: Content - Item duplication issue affecting localization of relational fields

### LINKED ISSUE #3820: Content - Item duplication issue affecting localization of relational fields
## Problem

When an item is duplicated, eg. EN-NZ version of the new copy incorrectly pulls the field value from the EN-AU version of the original item for its **One-to-One relational** field. It should be pointing to the EN-NZ value from the original item.

This issue also affects items created via API and seems to have started occurring around September 29th (AEST).

## Screenshots/video demo

https://github.com/user-attachments/assets/cb83219c-cf96-428d-a2fd-742ddbd02ae7

## Steps to reproduce

1. Take an existing item with multiple locales eg. EN-AU, EN-NZ, and with a relational field (eg. One-to-One "Form" field) 
2. Duplicate the item.
3. Examine the language/locale of the relational field when switch to the other locale eg. EN-NZ localization of the newly duplicated item.
4. Observe that the One-to-One field (switch to NZ version) is incorrectly set to the original item's EN-AU value.

Here's a [sample copied item](https://8-82d0f8aa87-9p0kv5.manager.zesty.io/content/6-cafbdf99b4-3sgscn/7-a6e386eeb6-zsws6z) for review.

## Expected behavior

When an item (having multiple locales) with relational field is duplicated, the relational field's language/locale of the duplicated item (switch to other locale version) should pick up the correct locale

### PR DESCRIPTION
**Pull request by geodem127**
## Root Cause:
When an item is duplicated, the system incorrectly loads the default language version instead of the version corresponding to the user's currently active language. This causes a mismatch between the UI display and the intended language of the new item.

## Fix:
Updated the duplication logic to correctly identify and use the language-specific ZUID of the item being copied, ensuring the UI displays the proper language version upon duplication.

https://github.com/user-attachments/assets/1534422e-7851-4533-9a15-79232ae9d4d3

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx [hunk 1]
```diff
@@ -94,16 +97,25 @@ export const DuplicateItemDialog = ({ onClose }: DuplicateItemProps) => {
...
-        dispatch(fetchItems(modelZUID));
         refetchContentModels();
-        onClose();
-        history.push(
-          `/${
-            models?.find((model) => model?.ZUID === modelZUID)?.type === "block"
-              ? "blocks"
-              : "content"
-          }/${modelZUID}/${res.data.ZUID}`
+        Promise.resolve(dispatch(fetchItems(modelZUID))).then(
```
Comment (agalin920) [inline src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx]: Promise.resolve() isn’t doing anything useful here is it? because if dispatch(fetchItems(modelZUID)) already returns a promise. Wrapping a promise with Promise.resolve() simply returns the same promise which is just redundant. 

If dispatch were synchronous, the .then() would still run immediately on the next microtask, giving the false impression of waiting for async work.

**Review by agalin920 — CHANGES_REQUESTED** [review]

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx (hunk 1 above)
Comment (geodem127) [reply src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/DuplicateItemDialog.tsx]: Agreed. The Promise.resolve() is only needed because TypeScript incorrectly infers the return type of the dispatched thunk. 
 I'll replace it with `// @ts-ignore `to directly suppress the error.

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx [hunk 2]
```diff
@@ -68,11 +69,12 @@ export const LanguageSelector = () => {
...
 
-  const activeLanguage = languages?.find(
-    (lang) => lang.ID === item?.meta?.langID
-  ) || {
-    code: "en-US",
-  };
+  useEffect(() => {
+    if (!isLoadingLanguages) {
+      const lang = languages?.find((lang) => lang.ID === item?.meta?.langID);
+      if (lang) setActiveLanguage(lang);
```
Comment (finnar-bin) [inline src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx]: Use block scopes instead of one-liners

**Review by finnar-bin — CHANGES_REQUESTED** [review]

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx (hunk 2 above)
Comment (geodem127) [reply src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx]: Updated

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx [hunk 3]
```diff
@@ -52,6 +52,7 @@ export const LanguageSelector = () => {
   const item = useSelector(
     (state: AppState) => state.content[itemZUID] as ContentItem
   );
+  const [activeLanguage, setActiveLanguage] = useState({ code: "en-US" });
 
   const onSelect = (langId: string) => {
     dispatch(selectLang(langId));
```
Comment (agalin920) [inline src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx:57]: we have this selectLang on select. should we not be using this to set the active lang? is there not a redux store that already supports this that we can select from?

**Comment by agalin920** [comment]
So i see this PR aims to redirect to the corresponding locale when duplicating an item. But the ticket in question states

"When an item is duplicated, eg. EN-NZ version of the new copy incorrectly pulls the field value from the EN-AU version of the original item for its One-to-One relational field"

What that sounds more like is that the item duplication is not pulling the correct values per locale. Is this not the case and in reality the reporter is mistaken?

**Review by agalin920 — CHANGES_REQUESTED** [review]

**Comment by geodem127** [comment]
> So i see this PR aims to redirect to the corresponding locale when duplicating an item. But the ticket in question states
> 
> "When an item is duplicated, eg. EN-NZ version of the new copy incorrectly pulls the field value from the EN-AU version of the original item for its One-to-One relational field"
> 
> What that sounds more like is that the item duplication is not pulling the correct values per locale. Is this not the case and in reality the reporter is mistaken?

The item duplication is actually working correctly—the new EN-NZ item properly gets its values from the original EN-NZ item. The problem is that after the duplication succeeds, the user is incorrectly redirected to view the new item in the default locale (e.g., EN-AU) instead of the locale they duplicated from (EN-NZ).

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx (hunk 3 above)
Comment (geodem127) [reply src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/LanguageSelector.tsx:57]: Yes, you're correct. The current implementation now uses the `selectLang` selector. The more complex approach was a remnant of an initial attempt to address a UI flicker, which fell outside the scope of this PR.

Since that issue wasn't part of the original report, I've removed that logic to keep the fix focused.

**Review by agalin920 — APPROVED** [review]

**Review by finnar-bin — APPROVED** [review]
