### PR TITLE
fixed missing instance api, swapped list to be circle

### LINKED ISSUE #639: Instant API link missing for content items
**Describe the bug**
The Instant API link can be seen in the Schema section for the Content Model but it is not shown in the Content section for single content items.

**To Reproduce**
1. Go to Content
2. Click on an item to see it's content fields
3. See right hand sidebar missing Instant API link

Schema:
Screen Shot 2021-04-07 at 11 47 27 AM

Content:
Screen Shot 2021-04-07 at 11 46 44 AM

### PR DESCRIPTION
**Pull request by d88naimi**
fixed missing api in content view 
swapped list bullets to circles to be consistent with other pages. 
fixes #639

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/QuickView/QuickView.js [hunk 1]
```diff
@@ -68,7 +68,7 @@ export const QuickView = React.memo(function QuickView(props) {
                 )}
               </span>
             </li>
-            {props.basicApi ? (
+            {codeAccess && (
```
Comment (shrunyan) [inline src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/QuickView/QuickView.js:71]: Does this short hand `&&` condition have the issue of displaying `0` when the user does not have code acess?

Comment (d88naimi) [reply src/apps/content-editor/src/app/views/ItemEdit/Content/Actions/Widgets/QuickView/QuickView.js:71]: No, if there is no access then json link does not render

**Review by shrunyan — APPROVED** [review]
