### PR TITLE
[#3444] Content: Create Redirect on URL Path Update

### LINKED ISSUE #3444: Content: Create Redirect on URL Path Update
# Problem
Content item URLs (paths/slugs) are often updated for various reasons, such as SEO improvements or content revisions reflecting external events. When a content item's URL path changes, the original URL currently becomes invalid and leads to a 404 page for anyone trying to access it. This leads to visitors using old bookmarks or links encountering 404 "Not Found" errors, which provides a poor user experience and can negatively impact SEO rankings. 

Website owners have conveyed that they need a seamless way to ensure traffic to old URLs is automatically directed to the new location.

This is because currently, creating the necessary redirect involves a cumbersome, manual process outside the content editing workflow: the user must remember the change, note the old path, navigate to the Redirects App, and manually create the rule. This process is inefficient, prone to human error (forgetting to create the redirect or recording the wrong path), and adds significant overhead to routine content updates. 

**The core issue is the lack of an integrated mechanism to assist with or automate redirect creation when a URL path changes.** 

# Solution 
Our system will now detect when a content item's URL path is changed upon publish and will ask the user if they want to create a 301 permanent redirect from the old path to the new path. 

Image

# Figma
https://www.figma.com/design/9tiAwQg179ezJH48diVdph/Redirects-App?node-id=60-48961&m=dev&t=X9cqEkZigmLQs57v-1

### PR DESCRIPTION
**Pull request by geodem127**
- [x] Integrated a DataGrid table within the SEO tab of the content editor to display redirects associated with a content item.
- [x] Enabled the ability to create, edit, and delete redirects directly from the SEO tab, including error handling for each operation.
- [x] Implemented logic to detect changes in the content item's path and prompt the user to optionally create a redirect to the new URL.

https://github.com/user-attachments/assets/8b530bec-0d9b-4764-a41b-e23e48ff5967

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx [hunk 1]
```diff
@@ -135,6 +150,54 @@ export const ItemEditHeaderActions = ({
...
+        isActive: ver?.web?.versionZUID === activePublishing?.versionZUID,
+      }))
+      .sort((a, b) => {
+        return (
+          new Date(b?.publishedAt).getTime() -
+          new Date(a?.publishedAt).getTime()
+        );
+      });
+
+    if (publishedItemVersions?.length < 2) return;
```
Comment (finnar-bin) [inline src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx:177]: What is this guarding for?

File: src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx [hunk 2]
```diff
@@ -135,6 +150,54 @@ export const ItemEditHeaderActions = ({
...
     );
 
+  useEffect(() => {
+    if (
+      isLoadingVersions ||
+      isFetchingVersions ||
+      isFetching ||
+      !isCheckingUrlPathChange
+    )
+      return;
```
Comment (finnar-bin) [inline src/apps/content-editor/src/app/views/ItemEdit/components/ItemEditHeader/ItemEditHeaderActions.tsx]: I suggest formatting this properly, it kind of looks confusing at a glance. Maybe make sure it's at least on the same line above or add an empty line after the return

File: src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,183 @@
...
+};
+
+export type ChangeDialogProps = {
+  open: boolean;
+  onClose: () => void;
+  redirect?: ChangeRedirectProps | null;
+  newPath?: string;
+};
+
+export const ChangeDialog: FC<ChangeDialogProps> = ({
```
Comment (finnar-bin) [inline src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx:37]: I suggest naming this component into something more descriptive of what it does, like in this case, what kind of change is this dialog doing or is for. ChangeDialog to me kind of sounds unclear on what it change the dialog does.

File: src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx [hunk 4]
```diff
@@ -0,0 +1,183 @@
...
+  target: string;
+  path: string;
+  code: RedirectsCodes;
+};
+
+export type ChangeDialogProps = {
+  open: boolean;
+  onClose: () => void;
+  redirect?: ChangeRedirectProps | null;
+  newPath?: string;
```
Comment (finnar-bin) [inline src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx]: Shouldn't these 2 be required props? There's no point showing this dialog component if these 2 data aren't present.

File: src/apps/seo/src/app/components/RedirectsDialogProvider/index.tsx [hunk 5]
```diff
@@ -68,15 +77,25 @@ const RedirectsDialogContextProvider = ({
   const [createFormOpen, setCreateFormOpen] = useState<boolean>(false);
   const [errorDialogOpen, setErrorDialogOpen] = useState<boolean>(false);
   const [deleteDialogOpen, setDeleteDialogOpen] = useState<boolean>(false);
+  const [changeDialogOpen, setChangeDialogOpen] = useState<boolean>(false);
+  const [isInternal, setIsInternal] = useState<boolean>(false);
```
Comment (finnar-bin) [inline src/apps/seo/src/app/components/RedirectsDialogProvider/index.tsx:81]: What is this for and why are we only checking for internal redirects?

**Review by finnar-bin — CHANGES_REQUESTED** [review]

File: src/apps/seo/src/app/components/RedirectsDialogProvider/index.tsx (hunk 5 above)
Comment (geodem127) [reply src/apps/seo/src/app/components/RedirectsDialogProvider/index.tsx:81]: This check is used to determine the user's accessibility to the create form, specifically identifying if the redirect being processed is part of an internal workflow—such as content or SEO redirects.
For these internal cases, the form's targetType and targetPath fields are locked and set to read-only.

File: src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx (hunk 4 above)
Comment (geodem127) [reply src/apps/seo/src/app/components/RedirectsDialogProvider/ChangeDialog.tsx]: Updated

**Review by finnar-bin — APPROVED** [review]

**Review by agalin920 — APPROVED** [review]
