### PR TITLE
[#3973]: Content - Application Crash When Viewing Content Items

### LINKED ISSUE #3973: [Content] - Application Crash When Viewing Content Items
## Problem
Clicking the "View Content" button in the schema causes the application to crash instead of navigating to the selected content item. This critical navigation failure also disrupts automated testing workflows.

## Screenshots
https://github.com/user-attachments/assets/b3468fa1-1c83-4b2d-b780-b9bcc915b54e

## Steps to reproduce

1. Navigate to the schema management page:

> - Staging: https://8-f48cf3a682-7fthvk.manager.stage.zesty.io/schema
> - Development:  https://8-f48cf3a682-7fthvk.manager.dev.zesty.io/schema

8cf3a682-7fthvk.manager.dev.zesty.io/schema
2. Open any list item (excluding block items)
3. Click the "View Content" action button
4. Observe application crash/error instead of successful navigation

## Expected behavior
The application should properly route to and display the selected content.

## Actual Behavior
Application crashes immediately after clicking "View Content," preventing navigation to the target content.

### LINKED ISSUE #3974: Error: Country code must be exactly 2 characters, instead received "".
Sentry Issue: [MANAGER-UI-2HB](https://zestyio.sentry.io/issues/7209692911/?referrer=github_integration)

```
React ErrorBoundary Error: Country code must be exactly 2 characters, instead received "".
  at Flag (./src/shell/components/Flag.tsx:9:3)
  at None (span)
  at None (button)
  at None (div)
  at ItemListFilters (./src/apps/content-editor/src/app/views/ItemList/ItemListFilters.tsx:30:7)
...
(45 additional frame(s) were not displayed)

Error: Country code must be exactly 2 characters, instead received "".
  at flagEmoji (./src/shell/components/Flag.tsx:15:13)
  at Flag (./src/shell/components/Flag.tsx:13:21)
...
(8 additional frame(s) were not displayed)
```

### LINKED ISSUE #3982: Content UI error "Country code must be exactly 2 characters"
Users are reporting a high-frequency, intermittent error when navigating to multi-page content items. The UI fails to load and displays a validation error regarding the country code, even when the user is navigating via standard UI clicks rather than manual URL manipulation.
It takes a lot of page refresh to have it  load sucessfully.

Error Message
`Error: Country code must be exactly 2 characters, instead received "".
`

multipage [content link](https://8-566cdeb-8gqvkj.manager.zesty.io/content/6-d8a9d2e6ae-bxhm4k)

**Screenshot** error:

Image

### PR DESCRIPTION
**Pull request by geodem127**
RCA:
- The Flag component throws an unhandled error when receiving an invalid or missing country code, causing application crashes.

FIX:
- Modified the component to safely handle invalid inputs by returning null instead of throwing an error.

NOTE: Also resolves failing Cypress tests affected by this error

### CODE REVIEW

File: src/shell/components/Flag.tsx [hunk 1]
```diff
@@ -13,9 +13,7 @@ export const getCountryCode = (langCode: string) => {
 export const Flag = ({ countryCode }: { countryCode: string }) => {
   const flagEmoji = useMemo(() => {
     if (!countryCode || countryCode.length !== 2) {
-      throw new Error(
-        `Country code must be exactly 2 characters, instead received "${countryCode}".`
-      );
```
Comment (finnar-bin) [inline src/shell/components/Flag.tsx:18]: @geodem127 this was purposely added since there should never be any scenario where a country code is less than 2 characters.

**Review by finnar-bin — APPROVED** [review]
