### PR TITLE
Handle case where Related Model 404s

### LINKED ISSUE #3637: TypeError: Cannot read properties of undefined (reading 'ZUID')
Sentry Issue: [MANAGER-UI-2E5](https://zestyio.sentry.io/issues/6720647905/?referrer=github_integration)

```
React ErrorBoundary Error: Cannot read properties of undefined (reading 'ZUID')
  at ActiveItem (./src/shell/components/RelationalFieldBase/ActiveItem/index.tsx:58:5)
  at RelationalFieldBase (./src/shell/components/RelationalFieldBase/index.tsx:36:3)
  at FieldShell (./src/apps/content-editor/src/app/components/Editor/Field/FieldShell.tsx:59:3)
  at qb (./src/apps/content-editor/src/app/components/Editor/Field/Field.tsx:85:3)
  at EA (./src/apps/content-editor/src/app/components/Editor/Editor.js:25:3)
...
(45 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'ZUID')
  at d (./src/shell/components/RelationalFieldBase/ActiveItem/index.tsx:244:43)
...
(5 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by agalin920**

### CODE REVIEW

File: src/shell/components/RelationalFieldBase/ActiveItem/index.tsx [hunk 1]
```diff
@@ -240,7 +240,7 @@ export const ActiveItem = memo(
 
     // Ensure item is fetched if it wasn't included in the initial 100-item fetch
     useEffect(() => {
-      if (contentItem) return;
+      if (contentItem || !relatedModelData?.ZUID || !itemZUID) return;
```
Comment (shrunyan) [inline src/shell/components/RelationalFieldBase/ActiveItem/index.tsx:243]: What is this going to do to the user experience? If the related model 404s and we exit without the content item is it going to be a blank field?

Comment (agalin920) [reply src/shell/components/RelationalFieldBase/ActiveItem/index.tsx:243]: @shrunyan It would show the ZUID with the word (deleted) since it was unable to resolve the item

e.g 7-12412412 (deleted)

**Review by shrunyan — APPROVED** [review]
