### PR TITLE
fix: Content: SEO Meta Description Displays that there are excess characters when there are none

### LINKED ISSUE #2501: Content: SEO Meta Description Displays that there are excess characters when there are none
**Bug:**
SEO Meta Description Displays that there are excess characters when there are none
See Loom: https://www.loom.com/share/33c13fa684b94f3a88111e9c7bfad2f9

**Solution**
Do not display that there are excess characters unless there actually are excess characters

### PR DESCRIPTION
**Pull request by glespinosa**
This will also solve problem in Meta Title, Meta Keywords, Navigation Link Text not only in the Meta Descriptions because they share same issues regarding excess characters

[screencast-8-aaeffee09b-7w6v22.manager.dev.zesty.io_8080-2024.02.06-09_19_45.webm](https://github.com/zesty-io/manager-ui/assets/44116036/828dea4e-4a74-4d69-a4eb-39e715f7257c)

Closes #2501 #2502

### CODE REVIEW

**Review by theofficialnar — COMMENTED** [review]
@glespinosa did you check with @zcolah if the expected behavior here is to automatically trim the user input instead of retaining the excess characters and letting the user fix it themselves before it gets saved?

**Comment by zcolah** [comment]
> @glespinosa did you check with @zcolah if the expected behavior here is to automatically trim the user input instead of retaining the excess characters and letting the user fix it themselves before it gets saved?

@theofficialnar currently this is the approach we are taking as it is the behavior that was already being followed for the other fields on the SEO Tab. We definitely want an error blurb like experience for SEO in the near future though.

**Review by theofficialnar — APPROVED** [review]

File: src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/MetaDescription.js [hunk 1]
```diff
@@ -40,6 +41,10 @@ export default connect()(function MetaDescription({
       }
 
       setError(message);
+
+      if (isSaving) {
```
[the remark this answers is not in the document]
Comment (glespinosa) [reply src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/MetaDescription.js:45]: yes for now it's relying on the useEffect since everytime the user is saving that's the only time I can rerun the onChange function to check the characters condition on excess.

File: src/shell/store/content.js [hunk 2]
```diff
@@ -406,7 +406,15 @@ export function saveItem(itemZUID, action = "") {
...
     }
-
+    if (item.web.metaTitle) {
+      item.web.metaTitle = item.web.metaTitle.slice(0, 150);
+    }
+    if (item.web.metaLinkText) {
+      item.web.metaLinkText = item.web.metaLinkText.slice(0, 150);
+    }
+    if (item.web.metaKeywords) {
+      item.web.metaKeywords = item.web.metaKeywords.slice(0, 250);
```
Comment (theofficialnar) [inline src/shell/store/content.js:416]: Why is 250 here? The ui character counter says it's 255.
image

Comment (glespinosa) [reply src/shell/store/content.js]: done updating changes

File: src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/MetaDescription.js (hunk 1 above)
[the remark this answers is not in the document]
Comment (glespinosa) [reply src/apps/content-editor/src/app/views/ItemEdit/Meta/ItemSettings/settings/MetaDescription.js]: @agalin920 I removed now the useEffect on every component and let the useEffect inside of ItemSettings do the work of removing the errors while on there are on saving... Then i slice all the props base on the number of allowed character on the properties in the /shell/store/content.js

File: src/shell/store/content.js [hunk 3]
```diff
@@ -406,7 +406,15 @@ export function saveItem(itemZUID, action = "") {
     if (item.web.metaDescription) {
       item.web.metaDescription = item.web.metaDescription.slice(0, 160);
     }
-
+    if (item.web.metaTitle) {
+      item.web.metaTitle = item.web.metaTitle.slice(0, 150);
```
Comment (shrunyan) [inline src/shell/store/content.js:410]: why is this being sliced at 150 characters?

File: src/shell/store/content.js (hunk 2 above)
Comment (shrunyan) [reply src/shell/store/content.js]: @glespinosa which character count did we settle on and why?

File: src/shell/store/content.js (hunk 3 above)
Comment (glespinosa) [reply src/shell/store/content.js:410]: My basis is on their UI like how the metadescription and other fields were slice.
image

File: src/shell/store/content.js (hunk 2 above)
Comment (glespinosa) [reply src/shell/store/content.js]: @shrunyan  I'm basing on the UI
image
