### PR TITLE
[Global]: search api call causes instances api service to crash

### LINKED ISSUE #3873: Global search api call causes instances api service to crash
## Problem

When loading manager-ui on specific instances with huge amounts of content items the instances api service crashes and restarts. 

Upon investigation, on load there is an api call to `/search/items?q=&limit=10000`, the 10k limit is quite huge, there are times that the api eventually responds and the raw resource size is 100mb+. Refreshing this instance several times would sometimes cause the instances api service to crash and restart.

## Screenshots

Image

## Steps to reproduce

1. Go to a customer instance with a lot of content items
2. Check network tab, on manager-ui load, there is an api call to the search endpoint with 10k limit
3. Leave it to try and resolve the response for a minute or so
4. Refresh the page then leave it again for a minute or so
5. Doing this over and over would eventually take down the service and the api calls to the instances api end up in CORS errors

## Expected behavior

The limit should be lowered down as 10k is too much

### PR DESCRIPTION
**Pull request by geodem127**
## RCA:
The search API was configured with an excessively high result limit (10,000) and no search term. This caused the request to fetch an unmanageably large dataset on page load, leading to frequent timeouts and failed responses.

## FIX:
- [ ] Removed the automatic API call on page load.
- [ ] Implemented a debounced search that only triggers on valid user input.
- [ ] Added sensible pagination/default limits to all search requests.
- [ ] Refactored the logic to leverage the Redux store for efficient state management.

https://github.com/user-attachments/assets/9f2551a1-12fc-4678-aa33-878e09dc9886

### CODE REVIEW

File: src/shell/components/GlobalSearch/index.tsx [hunk 1]
```diff
@@ -128,35 +131,57 @@ export const GlobalSearch = () => {
...
-    isFetchingBlocksResults;
+    isFetchingContentSearchResults;
+
+  useEffect(() => {
+    //Update models in store to provide access to other search hooks
+    dispatch(fetchModels());
+  }, []);
+
+  useEffect(() => {
+    if (isEmpty(apiQueryTerm)) return setSearchedContents([]);
```
Comment (finnar-bin) [inline src/shell/components/GlobalSearch/index.tsx]: Prefer block scope

File: src/shell/components/GlobalSearch/index.tsx [hunk 2]
```diff
@@ -128,35 +131,57 @@ export const GlobalSearch = () => {
...
+    //Update contents in store to provide access to other search hooks
+    dispatch(searchItems(apiQueryTerm))
+      //@ts-ignore
+      .then((res) => {
+        if (!!res?.data?.length) {
+          setSearchedContents(res?.data);
+        } else {
+          setSearchedContents([]);
+        }
+        setIsFetchingContentSearchResults(false);
```
Comment (finnar-bin) [inline src/shell/components/GlobalSearch/index.tsx:156]: Shouldn't this be placed on the `.finally()`?

File: src/shell/components/GlobalSearch/index.tsx [hunk 3]
```diff
@@ -356,7 +380,7 @@ export const GlobalSearch = () => {
     });
     const url = `/search?${searchParams.toString()}`;
 
-    // Do not save term as a recent keyword if it's empty
+    // Do not save term as a recent keyword if it's empty1
```
Comment (finnar-bin) [inline src/shell/components/GlobalSearch/index.tsx]: Typo at the end

File: src/shell/hooks/useSearchBlocksByKeyword.ts [hunk 4]
```diff
@@ -64,89 +73,145 @@ export const useSearchBlocksByKeyword = (): SearchResult => {
...
-      Object.fromEntries(modelsRaw?.map((model) => [model?.ZUID, model])),
-    [modelsRaw]
-  );
+  const normalizedSearchTerm = searchTerm.toLowerCase()?.trim();
+  const showAll = blockKeywords.includes(normalizedSearchTerm);
 
-  const normalizedSearch = searchTerm.toLowerCase()?.trim();
+  const blocks = useMemo<BlockModel[]>(() => {
+    const modelsArray = models ? Object.values(models) : [];
+    if (!modelsArray?.length) return [];
```
Comment (finnar-bin) [inline src/shell/hooks/useSearchBlocksByKeyword.ts]: Prefer block scope

File: src/shell/hooks/useSearchBlocksByKeyword.ts [hunk 5]
```diff
@@ -64,89 +73,145 @@ export const useSearchBlocksByKeyword = (): SearchResult => {
...
+
+  useEffect(() => {
+    // Fetch all block models and variants if user searches for "blockKeywords"
+    if (showAll && !!blocks?.length) {
+      setIsFetchingVariants(true);
+      Promise.all(
+        blocks?.map((block) =>
+          dispatch(fetchItems(block?.ZUID, { limit: 1000 }))
+        )
+      ).then(() => {
```
Comment (finnar-bin) [inline src/shell/hooks/useSearchBlocksByKeyword.ts]: I would place this inside the `finally()` to make sure the flag still gets set to false if this fails

File: src/shell/views/SearchPage/SearchPage.tsx [hunk 6]
```diff
@@ -48,17 +48,14 @@ export const SearchPage: FC = () => {
   const keyword = params.get("q") || "";
   const instanceId = useSelector((state: any) => state.instance.ID);
   const ecoId = useSelector((state: any) => state.instance.ecoID);
+  const allModels = useSelector((state: any) => state.models);
```
Comment (finnar-bin) [inline src/shell/views/SearchPage/SearchPage.tsx]: Use the `AppState` type instead of any

**Review by finnar-bin — CHANGES_REQUESTED** [review]

File: src/shell/components/GlobalSearch/index.tsx (hunk 1 above)
Comment (geodem127) [reply src/shell/components/GlobalSearch/index.tsx]: Updated

File: src/shell/components/GlobalSearch/index.tsx (hunk 2 above)
Comment (geodem127) [reply src/shell/components/GlobalSearch/index.tsx:156]: Updated

File: src/shell/components/GlobalSearch/index.tsx (hunk 3 above)
Comment (geodem127) [reply src/shell/components/GlobalSearch/index.tsx]: Updated

File: src/shell/hooks/useSearchBlocksByKeyword.ts (hunk 4 above)
Comment (geodem127) [reply src/shell/hooks/useSearchBlocksByKeyword.ts]: Updated

File: src/shell/hooks/useSearchBlocksByKeyword.ts (hunk 5 above)
Comment (geodem127) [reply src/shell/hooks/useSearchBlocksByKeyword.ts]: Updated

File: src/shell/views/SearchPage/SearchPage.tsx (hunk 6 above)
Comment (geodem127) [reply src/shell/views/SearchPage/SearchPage.tsx]: Updated

**Comment by finnar-bin** [comment]
@geodem127 is there any reason why the base branch has been changed? There's currently 300+ changed files

**Comment by geodem127** [comment]
> @geodem127 is there any reason why the base branch has been changed? There's currently 300+ changed files

I'm not sure what happened, but I’ve already switched it back to dev.

**Review by finnar-bin — APPROVED** [review]

**Review by agalin920 — APPROVED** [review]

**Comment by shrunyan** [comment]
Why is there so much code changed in the PR when the core of it, as descibed, is going from `10000` to `1000`? i.e. I'm expecting a single line change PR.

> no default search term. 

Also not sure what that means. Why would search have a default term? How would we know what a baseline default term is that meets a users expectations.

**Comment by geodem127** [comment]
> Why is there so much code changed in the PR when the core of it, as descibed, is going from `10000` to `1000`? i.e. I'm expecting a single line change PR.
> 
> > no default search term.
> 
> Also not sure what that means. Why would search have a default term? How would we know what a baseline default term is that meets a users expectations.

The other modifications (debounce, filtering block items, and the UI icon) were initially part of the PR but have since been removed. The diff now primarily shows the core architectural change from RTK Query to Redux dispatch.

Just  to clarify the RCA description: "no default search term" was a typo. It should read "no search term specified"
