### PR TITLE
fixing empty item content

### LINKED ISSUE #812: A blank Content item is creating an empty row in ItemList table view
**Describe the bug**
When creating a new item for a Multi Page Model and redirecting or leaving the unsaved item to another view, a empty row will be generated.

Also if you select the empty item and add text and create the item a new item will be created while the empty row is appended down the table. 

**To Reproduce**
http://8-f48cf3a682-7fthvk.manager.dev.zesty.io:8080/content/6-a2edaefaf7-hs9bdz
Advanced Publishing Example > create an item > leave empty > click back to Advanced Publishing Example > you will see an empty row being displayed, which leads to a confusing experience.

**Screen Share**
https://www.screencast.com/t/prtg390s

**Expected behavior**
When hitting back or redirecting to a different view, no visual changes should populate.

**Alternative solution **
Render the unsaved changes modal 
Screen Shot 2021-07-12 at 10 12 38 AM

**Screenshots**
Screen Shot 2021-07-12 at 10 03 49 AM

### PR DESCRIPTION
**Pull request by d88naimi**
fixes #812 
Screen Shot 2021-07-17 at 5 09 41 AM

### CODE REVIEW

File: src/apps/content-editor/src/app/views/ItemList/ItemList.js [hunk 1]
```diff
@@ -82,7 +83,11 @@ export default connect((state, props) => {
   const [initialLoading, setInitialLoading] = useState(false);
   const [backgroundLoading, setBackgroundLoading] = useState(false);
 
-  const [items, setItems] = useState([]);
+  // const [items, setItems] = useState([]);
```
Comment (nibblebot) [inline src/apps/content-editor/src/app/views/ItemList/ItemList.js:86]: remove comment

**Review by nibblebot — CHANGES_REQUESTED** [review]

**Review by shrunyan — APPROVED** [review]
