### PR TITLE
fixed broken content nav search

### LINKED ISSUE #983: Content app search bug - does not allow user to type spaces in search field
**Describe the bug**
The search feature in the Content App navigation tree does not allow the user to type in spaces. Blocking users from directly searching for the content item they are looking for. 

**To Reproduce**
1. Go to content app
2. Click into the search field inside the content app navigation tree
3. As you begin typing you'll notice the letters are accepted, however, spaces are completely blocked.

**Expected behavior**
when typing in the search field all characters are accepted, including spaces.

**Video**
https://www.loom.com/share/6846cbb8582f4887ac02e834228fefd0

### PR DESCRIPTION
**Pull request by d88naimi**
Fixed broken content nav search. Didn't allow user to add a space when searching.
fixes #983 

Added DS Notice No results found
Screen Shot 2022-03-03 at 11 03 42 AM

### CODE REVIEW

File: src/apps/content-editor/src/app/components/Nav/ContentNav.js [hunk 1]
```diff
@@ -162,10 +163,8 @@ export function ContentNav(props) {
         </div>
         {searchTerm && filteredItems.length === 0 && (
           <>
-            <h1 className={cx(styles.NavTitle, styles.NoResults)}>
-              {" "}
-              No Search Results for "{searchTerm}"{" "}
-            </h1>
+            <Notice>No Search Results for "{searchTerm}</Notice>
```
Comment (agalin920) [inline src/apps/content-editor/src/app/components/Nav/ContentNav.js:166]: Missing closing "

**Review by shrunyan — APPROVED** [review]
